version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql

  php:
    image: php:8.1-apache
    container_name: php-apache
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
